import type { Locale } from "./types";

export const importCopy = {
  ru: {
    pageTitle: "Импорт выписки",
    pageSubtitle: "Загрузите XLSX и проверьте операции перед добавлением.",
    refresh: "Обновить",
    uploadTitle: "Проверьте банковскую выписку",
    uploadHelp: "Выберите XLSX-файл. Он будет обработан на сервере и не сохранится в браузере.",
    dropHelp: "Перетащите XLSX сюда или выберите файл",
    chooseFile: "Выбрать файл",
    uploadSelected: "Загрузить и проверить",
    uploading: "Загружаю и проверяю…",
    unsupportedFile: "Поддерживаются только файлы .xlsx.",
    uploadError: "Не удалось загрузить выписку.",
    reviewTitle: "Проверка операций",
    loadingPreview: "Загружаю сохранённый черновик…",
    previewError: "Не удалось загрузить черновик импорта.",
    totals: "Всего",
    ready: "Готово автоматически",
    needsReview: "Нужна проверка",
    duplicates: "Возможные дубли",
    errors: "Ошибки",
    excluded: "Исключено",
    uncategorized: "Без категории",
    work: "Рабочие / ФОП",
    savings: "Накопления",
    filterNeedsReview: "Нужна проверка",
    filterDuplicates: "Дубли",
    filterErrors: "Ошибки",
    filterUncategorized: "Без категории",
    filterReady: "Готово",
    filterExcluded: "Исключено",
    filterAll: "Все",
    merchantSearch: "Продавец",
    bankCategorySearch: "Категория банка",
    proposedCategory: "Предложенная категория",
    anyCategory: "Любая категория",
    reasonFilter: "Причина",
    anyReason: "Любая причина",
    applyFilters: "Применить фильтры",
    clearFilters: "Сбросить",
    showing: "Показано",
    of: "из",
    previous: "Назад",
    next: "Дальше",
    noRows: "В этой выборке операций нет.",
    amount: "Сумма",
    date: "Дата и время",
    merchant: "Продавец / описание",
    category: "Категория",
    bankCategory: "Категория банка",
    flow: "Тип операции",
    scope: "Область",
    reasons: "Причины",
    edit: "Проверить",
    close: "Закрыть",
    save: "Сохранить изменения",
    saving: "Сохраняю…",
    merchantName: "Название продавца",
    chooseCategory: "Выберите категорию",
    chooseSubcategory: "Выберите подкатегорию",
    noSubcategory: "Без подкатегории",
    noCategoryAction: "Оставить без категории",
    noCategoryHelp: "Операция будет импортирована без категории и останется видна для разбора позже.",
    includeInImport: "Включить операцию в импорт",
    excludeFromImport: "Исключить строку",
    includeDuplicate: "Всё равно импортировать",
    duplicateIncluded: "Дубль будет импортирован по вашему решению.",
    duplicateSkipped: "Этот дубль будет пропущен при импорте.",
    sameFileDuplicate: "Эта строка повторяет строку №{{row}} в этой выписке.",
    matchedTransaction: "Уже импортированная операция",
    incomingTransaction: "Операция из выписки",
    duplicateNote: "Не импортируем автоматически; вы можете включить операцию явно.",
    errorRowTitle: "Строку нельзя импортировать как есть",
    errorRowHelp: "Проверьте исходную выписку или исключите эту строку.",
    ruleSave: "Запомнить для будущих импортов",
    ruleSaveHelp: "Будущие операции этого продавца будут получать такое же предложение.",
    applyToMerchant: "Применить ко всем операциям этого продавца в текущей выписке",
    selectedRows: "Выбрано: {{count}}",
    selectPage: "Выбрать эту страницу",
    clearSelection: "Снять выбор",
    bulkAction: "Действие для выбранных",
    bulkAssignCategory: "Назначить категорию",
    bulkSetScope: "Изменить область",
    bulkSetFlow: "Изменить тип операции",
    bulkExclude: "Исключить выбранные",
    bulkIncludeDuplicates: "Импортировать выбранные дубли",
    bulkUncategorized: "Оставить без категории",
    bulkCorrection: "Применить исправление",
    applyBulk: "Выполнить действие",
    workingBulk: "Обновляю операции…",
    bulkNeedCategory: "Выберите категорию для выбранных операций.",
    changedRows: "Изменено операций: {{count}}.",
    bulkConfirm: "Изменить {{count}} выбранных операций?",
    account: "Счёт для импорта",
    chooseAccount: "Выберите счёт",
    accountsLoading: "Загружаю счета…",
    noAccounts: "Нет активных счетов. Добавьте или активируйте счёт перед импортом.",
    accountsError: "Не удалось загрузить счета.",
    confirmTitle: "Готово к импорту",
    expectedImported: "Будет добавлено",
    duplicatesWillSkip: "Дублей будет пропущено",
    errorsBlockConfirm: "Сначала исключите все строки с ошибками.",
    confirmWarning: "Операции без категории будут импортированы без категории.",
    confirm: "Подтвердить импорт",
    confirming: "Подтверждаю…",
    confirmError: "Не удалось подтвердить импорт.",
    resultTitle: "Импорт завершён",
    alreadyConfirmedTitle: "Этот импорт уже подтверждён",
    created: "Добавлено операций",
    resultExcluded: "Исключено строк",
    resultDuplicates: "Найдено дублей",
    resultUncategorized: "Без категории",
    resultWork: "Рабочие / ФОП",
    goDashboard: "Перейти на дашборд",
    startOver: "Загрузить другую выписку",
    fileLabel: "Файл",
    period: "Период",
    emptyPeriod: "Период не определён",
    statusReady: "Готово",
    statusNeedsReview: "Нужна проверка",
    statusDuplicate: "Дубль",
    statusError: "Ошибка",
    statusExcluded: "Исключено",
    statusUncategorized: "Без категории",
    statusWork: "ФОП",
    flowPurchase: "Покупка",
    flowCashWithdrawal: "Снятие наличных",
    flowCashExpense: "Наличный расход",
    flowOwnTransfer: "Перевод между своими счетами",
    flowSavings: "Накопления",
    flowWifeTransfer: "Перевод жене",
    flowPersonTransfer: "Перевод человеку",
    flowRequisites: "Платёж по реквизитам",
    flowRefund: "Возврат",
    flowIncome: "Доход",
    flowSubscription: "Подписка",
    flowWork: "Рабочая операция",
    flowOther: "Другое",
    scopeFamily: "Семья",
    scopePersonal: "Личные расходы",
    scopeWork: "Рабочая / ФОП",
    reason_new_merchant: "Новый продавец",
    reason_large_amount: "Крупная сумма",
    reason_large_supermarket: "Крупная покупка в супермаркете",
    reason_person_transfer: "Перевод физлицу",
    reason_wife_transfer: "Перевод жене",
    reason_requisites_payment: "Платёж по реквизитам",
    reason_low_confidence: "Низкая уверенность",
    reason_work_fop_candidate: "Возможная рабочая операция",
    reason_duplicate: "Возможный дубль",
    reason_uncategorized: "Не выбрана категория",
    reason_rule_conflict: "Правила предлагают разные значения",
    reason_parse_error: "Ошибка разбора",
    reason_unknown: "Требует проверки",
    flowUnknown: "Не указан",
    scopeUnknown: "Не указана",
    description: "Описание",
    categoryLoadError: "Не удалось загрузить категории.",
    rowSaveError: "Не удалось сохранить изменения.",
    bulkError: "Не удалось выполнить массовое действие.",
    requestError: "Не удалось выполнить запрос. Проверьте соединение и повторите попытку.",
  },
  uk: {
    pageTitle: "Імпорт виписки",
    pageSubtitle: "Завантажте XLSX і перевірте операції перед додаванням.",
    refresh: "Оновити",
    uploadTitle: "Перевірте банківську виписку",
    uploadHelp: "Оберіть XLSX-файл. Його буде оброблено на сервері, він не зберігатиметься у браузері.",
    dropHelp: "Перетягніть XLSX сюди або оберіть файл",
    chooseFile: "Обрати файл",
    uploadSelected: "Завантажити й перевірити",
    uploading: "Завантажую та перевіряю…",
    unsupportedFile: "Підтримуються лише файли .xlsx.",
    uploadError: "Не вдалося завантажити виписку.",
    reviewTitle: "Перевірка операцій",
    loadingPreview: "Завантажую збережену чернетку…",
    previewError: "Не вдалося завантажити чернетку імпорту.",
    totals: "Усього",
    ready: "Готово автоматично",
    needsReview: "Потрібна перевірка",
    duplicates: "Можливі дублікати",
    errors: "Помилки",
    excluded: "Виключено",
    uncategorized: "Без категорії",
    work: "Робочі / ФОП",
    savings: "Накопичення",
    filterNeedsReview: "Потрібна перевірка",
    filterDuplicates: "Дублікати",
    filterErrors: "Помилки",
    filterUncategorized: "Без категорії",
    filterReady: "Готово",
    filterExcluded: "Виключено",
    filterAll: "Усі",
    merchantSearch: "Продавець",
    bankCategorySearch: "Категорія банку",
    proposedCategory: "Запропонована категорія",
    anyCategory: "Будь-яка категорія",
    reasonFilter: "Причина",
    anyReason: "Будь-яка причина",
    applyFilters: "Застосувати фільтри",
    clearFilters: "Скинути",
    showing: "Показано",
    of: "із",
    previous: "Назад",
    next: "Далі",
    noRows: "У цій вибірці немає операцій.",
    amount: "Сума",
    date: "Дата й час",
    merchant: "Продавець / опис",
    category: "Категорія",
    bankCategory: "Категорія банку",
    flow: "Тип операції",
    scope: "Область",
    reasons: "Причини",
    edit: "Перевірити",
    close: "Закрити",
    save: "Зберегти зміни",
    saving: "Зберігаю…",
    merchantName: "Назва продавця",
    chooseCategory: "Оберіть категорію",
    chooseSubcategory: "Оберіть підкатегорію",
    noSubcategory: "Без підкатегорії",
    noCategoryAction: "Залишити без категорії",
    noCategoryHelp: "Операцію буде імпортовано без категорії, і вона залишиться видимою для подальшого розбору.",
    includeInImport: "Додати операцію до імпорту",
    excludeFromImport: "Виключити рядок",
    includeDuplicate: "Усе одно імпортувати",
    duplicateIncluded: "Дублікат буде імпортовано за вашим рішенням.",
    duplicateSkipped: "Цей дублікат буде пропущено під час імпорту.",
    sameFileDuplicate: "Цей рядок повторює рядок №{{row}} у цій виписці.",
    matchedTransaction: "Уже імпортована операція",
    incomingTransaction: "Операція з виписки",
    duplicateNote: "Автоматично не імпортуємо; ви можете явно додати операцію.",
    errorRowTitle: "Рядок не можна імпортувати як є",
    errorRowHelp: "Перевірте вихідну виписку або виключіть цей рядок.",
    ruleSave: "Запам’ятати для майбутніх імпортів",
    ruleSaveHelp: "Майбутні операції цього продавця отримуватимуть таку саму пропозицію.",
    applyToMerchant: "Застосувати до всіх операцій цього продавця в поточній виписці",
    selectedRows: "Обрано: {{count}}",
    selectPage: "Обрати цю сторінку",
    clearSelection: "Зняти вибір",
    bulkAction: "Дія для обраних",
    bulkAssignCategory: "Призначити категорію",
    bulkSetScope: "Змінити область",
    bulkSetFlow: "Змінити тип операції",
    bulkExclude: "Виключити обрані",
    bulkIncludeDuplicates: "Імпортувати обрані дублікати",
    bulkUncategorized: "Залишити без категорії",
    bulkCorrection: "Застосувати виправлення",
    applyBulk: "Виконати дію",
    workingBulk: "Оновлюю операції…",
    bulkNeedCategory: "Оберіть категорію для вибраних операцій.",
    changedRows: "Змінено операцій: {{count}}.",
    bulkConfirm: "Змінити {{count}} вибраних операцій?",
    account: "Рахунок для імпорту",
    chooseAccount: "Оберіть рахунок",
    accountsLoading: "Завантажую рахунки…",
    noAccounts: "Немає активних рахунків. Додайте або активуйте рахунок перед імпортом.",
    accountsError: "Не вдалося завантажити рахунки.",
    confirmTitle: "Готово до імпорту",
    expectedImported: "Буде додано",
    duplicatesWillSkip: "Дублікатів буде пропущено",
    errorsBlockConfirm: "Спочатку виключіть усі рядки з помилками.",
    confirmWarning: "Операції без категорії буде імпортовано без категорії.",
    confirm: "Підтвердити імпорт",
    confirming: "Підтверджую…",
    confirmError: "Не вдалося підтвердити імпорт.",
    resultTitle: "Імпорт завершено",
    alreadyConfirmedTitle: "Цей імпорт уже підтверджено",
    created: "Додано операцій",
    resultExcluded: "Виключено рядків",
    resultDuplicates: "Знайдено дублікатів",
    resultUncategorized: "Без категорії",
    resultWork: "Робочі / ФОП",
    goDashboard: "Перейти до дашборду",
    startOver: "Завантажити іншу виписку",
    fileLabel: "Файл",
    period: "Період",
    emptyPeriod: "Період не визначено",
    statusReady: "Готово",
    statusNeedsReview: "Потрібна перевірка",
    statusDuplicate: "Дублікат",
    statusError: "Помилка",
    statusExcluded: "Виключено",
    statusUncategorized: "Без категорії",
    statusWork: "ФОП",
    flowPurchase: "Покупка",
    flowCashWithdrawal: "Зняття готівки",
    flowCashExpense: "Готівкова витрата",
    flowOwnTransfer: "Переказ між власними рахунками",
    flowSavings: "Накопичення",
    flowWifeTransfer: "Переказ дружині",
    flowPersonTransfer: "Переказ людині",
    flowRequisites: "Платіж за реквізитами",
    flowRefund: "Повернення",
    flowIncome: "Дохід",
    flowSubscription: "Підписка",
    flowWork: "Робоча операція",
    flowOther: "Інше",
    scopeFamily: "Родина",
    scopePersonal: "Особисті витрати",
    scopeWork: "Робоча / ФОП",
    reason_new_merchant: "Новий продавець",
    reason_large_amount: "Велика сума",
    reason_large_supermarket: "Велика покупка в супермаркеті",
    reason_person_transfer: "Переказ фізичній особі",
    reason_wife_transfer: "Переказ дружині",
    reason_requisites_payment: "Платіж за реквізитами",
    reason_low_confidence: "Низька впевненість",
    reason_work_fop_candidate: "Можлива робоча операція",
    reason_duplicate: "Можливий дублікат",
    reason_uncategorized: "Не вибрано категорію",
    reason_rule_conflict: "Правила пропонують різні значення",
    reason_parse_error: "Помилка розбору",
    reason_unknown: "Потрібна перевірка",
    flowUnknown: "Не вказано",
    scopeUnknown: "Не вказано",
    description: "Опис",
    categoryLoadError: "Не вдалося завантажити категорії.",
    rowSaveError: "Не вдалося зберегти зміни.",
    bulkError: "Не вдалося виконати масову дію.",
    requestError: "Не вдалося виконати запит. Перевірте з’єднання та спробуйте ще раз.",
  },
} satisfies Record<Locale, Record<string, string>>;

export type ImportCopy = typeof importCopy.ru;

export function interpolate(value: string, values: Record<string, string | number>): string {
  return value.replace(/\{\{(\w+)\}\}/g, (_, key: string) => String(values[key] ?? ""));
}
